branches:
  only: #this is a whitelist for branches to build on, add if you want to build on yours as well
    - dev
    - bob

matrix:
  include:
    - language: python
      python:
        - "3.8.0"
        - "3.9.1"
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      before_script:
        - cd backend_tests
      script:
        - python -m pycodestyle . --exclude=venv
        - python -m pytest -v
    
    - language: node_js
      node_js:
        - node
      before_install:
        - cd frontend
      install:
        - npm install 
      script:
        - npx eslint src
        - npm test